// Deterministic PCB-trace generator -> src/data/circuit.ts
// Traces run on a grid with 45° bends and end in node circles, like the letterhead watermark.
import { writeFileSync } from 'node:fs';
let seed = 20200916;
const rnd = () => (seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296;
const W = 1400, H = 800, G = 40;
const paths = [], nodes = [], pads = [];
const dirs = [[1,0],[0,1],[-1,0],[0,-1]];
for (let i = 0; i < 26; i++) {
  let x = Math.round((rnd() * W) / G) * G, y = Math.round((rnd() * H) / G) * G;
  let d = dirs[Math.floor(rnd() * 4)];
  const pts = [[x, y]];
  const segs = 3 + Math.floor(rnd() * 4);
  for (let s = 0; s < segs; s++) {
    const len = G * (2 + Math.floor(rnd() * 6));
    // 45° jog between straight segments
    if (s > 0) {
      const turn = rnd() < 0.5 ? 1 : -1;
      const nd = dirs[(dirs.indexOf(d) + turn + 4) % 4];
      const jog = G * (1 + Math.floor(rnd() * 2));
      x += (d[0] + nd[0]) * jog; y += (d[1] + nd[1]) * jog;
      pts.push([x, y]);
      if (rnd() < 0.5) d = nd;
    }
    x += d[0] * len; y += d[1] * len;
    pts.push([x, y]);
  }
  paths.push('M' + pts.map(p => p.join(' ')).join(' L'));
  nodes.push(pts[pts.length - 1]);
  if (rnd() < 0.5) pads.push(pts[0]);
}
const out = `// Generated by scripts/gen-circuit.mjs. Do not edit by hand.
export const circuit = { w: ${W}, h: ${H}, paths: ${JSON.stringify(paths)}, nodes: ${JSON.stringify(nodes)}, pads: ${JSON.stringify(pads)} };
`;
writeFileSync('src/data/circuit.ts', out);
console.log('circuit.ts:', paths.length, 'traces,', nodes.length, 'nodes,', pads.length, 'pads');
